# Blog settings
permalink: /article/:title


# My variables
name: Natasaha Hoare
description: Curator & Writer
google_verification: null

# Where are tags and categories displayed
category_page: '/blog/categories/'

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
