# Blog settings
permalink: /article/:year-:month-:day-:title

# My variables
name: Natasha Hoare
description: Curator & Writer
google_verification: null

# Where are tags and categories displayed
category_page: '/blog/categories/'

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]
encoding: UTF-8

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
encoding: utf-8
